name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Install vuepress
        run: npm install  vuepress
      - name: Build
        run: vuepress build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: .vuepress/dist
          path: .vuepress/dist.
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: .vuepress/dist
          path: .vuepress/dist.
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting --project ronaldnino-blog
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
